apiVersion: apps/v1
kind: Deployment
metadata:
  name: techsolutions-deployment
  namespace: default
  labels:
    app: techsolutions

spec:
  replicas: 3
  selector:
    matchLabels:
      app: techsolutions

  template:
    metadata:
      labels:
        app: techsolutions

    spec:
      containers:
      - name: techsolutions-container
        image: punnam2909/techsolutions:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: techsolutions-service
  namespace: default

spec:
  type: ClusterIP
  selector:
    app: techsolutions

  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
